version: '3.9'
services:
    web:
        container_name: harvest-michael
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/project
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.harvest-michael.entrypoints=https"
            - "traefik.http.routers.harvest-michael.rule=Host(`harvest-michael.cut.hcu-hamburg.de`)"
            - "traefik.http.routers.harvest-michael.tls=true"
            - "traefik.http.routers.harvest-michael.tls.certresolver=lets-encr"

networks:
    proxy:
        external: true
